#aws.access.key.id=foo
#aws.secret.access.key=bar

server:
  port: 8081

spring:
  # MySQL db configuration
  datasource:
    username: root
    password: '11234'
    url: jdbc:mysql://localhost:3306/raz?useLegacyDatetimeCode=false&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    #url: jdbc:mysql://localhost:3306/raz?useLegacyDatetimeCode=false&useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.jdbc.Driver
  # JPA & Hibernate configuration
  jpa:
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: none

